source "https://rubygems.org"

gem "lita"
gem "lita-ascii-art"
gem "lita-dice"
gem "lita-excuses"
gem "lita-flip"
gem "lita-google"
gem "lita-google-images"
gem "lita-karma"
gem "lita-pugbomb", :git => "git://github.com/ahayworth/lita-pugbomb.git", :branch => "doge_bomb"
gem "lita-slack"
gem "lita-stocks"
gem "lita-wikipedia"
gem "lita-xkcd"
